# Generated by JARVIS MB-199. Do not edit.
_jarvis_console() {
    local cur prev command candidates
    cur="${COMP_WORDS[COMP_CWORD]}"
    prev="${COMP_WORDS[COMP_CWORD-1]}"
    command=''
    for token in "${COMP_WORDS[@]:1}"; do
        if [[ " ask chat objectives goal-strategy objective work-items work-item open-loops resume-loop artifacts artifact technology-candidates experience-reflections procedural-playbooks skill-evolution evolution-review-queue evolution-review memory-review-queue memory-review mission-cycle operator-dashboard daily-workspace operator-outcomes command-reference completion readiness-dashboard doctor learning-report progress-report mission-workflow mission-feedback " == *" $token "* ]]; then
            command="$token"
            break
        fi
    done
    if [[ $prev == '--format' ]]; then
        COMPREPLY=( $(compgen -W "text json" -- "$cur") )
        return
    fi
    if [[ -z $command ]]; then
        COMPREPLY=( $(compgen -W "--format ask chat objectives goal-strategy objective work-items work-item open-loops resume-loop artifacts artifact technology-candidates experience-reflections procedural-playbooks skill-evolution evolution-review-queue evolution-review memory-review-queue memory-review mission-cycle operator-dashboard daily-workspace operator-outcomes command-reference completion readiness-dashboard doctor learning-report progress-report mission-workflow mission-feedback" -- "$cur") )
        return
    fi
    case "$command:$prev" in
        ask:--format) candidates="text json" ;;
        chat:--format) candidates="text json" ;;
        objectives:--format) candidates="text json" ;;
        goal-strategy:--format) candidates="text json" ;;
        objective:--action) candidates="resume pause block complete redefine-next-action" ;;
        objective:--format) candidates="text json" ;;
        work-items:--format) candidates="text json" ;;
        work-item:--action) candidates="create update resume pause block complete redefine-next-action" ;;
        work-item:--priority) candidates="p0 p1 p2 p3" ;;
        work-item:--format) candidates="text json" ;;
        open-loops:--format) candidates="text json" ;;
        resume-loop:--format) candidates="text json" ;;
        artifacts:--format) candidates="text json" ;;
        artifact:--action) candidates="register activate archive replace rollback" ;;
        artifact:--format) candidates="text json" ;;
        technology-candidates:--format) candidates="text json" ;;
        experience-reflections:--format) candidates="text json" ;;
        procedural-playbooks:--format) candidates="text json" ;;
        skill-evolution:--format) candidates="text json" ;;
        evolution-review-queue:--format) candidates="text json" ;;
        evolution-review:--action) candidates="approve reject sandbox needs-review rollback" ;;
        evolution-review:--format) candidates="text json" ;;
        memory-review-queue:--maintenance-action) candidates="consolidate archive expire" ;;
        memory-review-queue:--format) candidates="text json" ;;
        memory-review:--action) candidates="approve reject needs-review rollback" ;;
        memory-review:--format) candidates="text json" ;;
        mission-cycle:--format) candidates="text json" ;;
        operator-dashboard:--format) candidates="text json" ;;
        daily-workspace:--format) candidates="text json" ;;
        operator-outcomes:--format) candidates="text json" ;;
        command-reference:--format) candidates="text json" ;;
        completion:--shell) candidates="powershell bash zsh" ;;
        completion:--format) candidates="text json" ;;
        readiness-dashboard:--run-gate) candidates="quick standard" ;;
        readiness-dashboard:--format) candidates="text json" ;;
        doctor:--format) candidates="text json" ;;
        learning-report:--format) candidates="text json" ;;
        progress-report:--format) candidates="text json" ;;
        mission-workflow:--format) candidates="text json" ;;
        mission-feedback:--assessment) candidates="helpful partially-helpful not-helpful correction" ;;
        mission-feedback:--format) candidates="text json" ;;
        *) candidates='' ;;
    esac
    if [[ -z $candidates ]]; then
        case "$command" in
            ask) candidates="-h --help --session-id --mission-id --operator-identity-ref --canonical-user-ref --debug --format" ;;
            chat) candidates="-h --help --session-id --mission-id --message --operator-identity-ref --canonical-user-ref --debug --format" ;;
            objectives) candidates="-h --help --mission-id --format" ;;
            goal-strategy) candidates="-h --help --mission-id --session-id --operator-identity-ref --canonical-user-ref --format" ;;
            objective) candidates="-h --help --mission-id --session-id --action --next-action-ref --operator-identity-ref --canonical-user-ref --format" ;;
            work-items) candidates="-h --help --mission-id --format" ;;
            work-item) candidates="-h --help --mission-id --session-id --action --work-item-ref --next-action-ref --depends-on --clear-dependencies --priority --blocker-ref --operator-identity-ref --canonical-user-ref --format" ;;
            open-loops) candidates="-h --help --mission-id --format" ;;
            resume-loop) candidates="-h --help --mission-id --open-loop-ref --session-id --operator-identity-ref --canonical-user-ref --format" ;;
            artifacts) candidates="-h --help --mission-id --format" ;;
            artifact) candidates="-h --help --mission-id --session-id --action --artifact-ref --artifact-version --work-item-ref --replacement-artifact-ref --rollback-plan-ref --operator-identity-ref --canonical-user-ref --format" ;;
            technology-candidates) candidates="-h --help --evolution-db --limit --format" ;;
            experience-reflections) candidates="-h --help --memory-db --mission-id --workflow-profile --limit --format" ;;
            procedural-playbooks) candidates="-h --help --memory-db --workflow-profile --review-status --limit --format" ;;
            skill-evolution) candidates="-h --help --memory-db --evolution-db --skill-id --version --workflow-profile --route --domain --limit --format" ;;
            evolution-review-queue) candidates="-h --help --evolution-db --limit --format" ;;
            evolution-review) candidates="-h --help --evolution-db --proposal-id --action --operator-ref --evidence-ref --proposed-test --rollback-plan-ref --risk-acceptance --note --format" ;;
            memory-review-queue) candidates="-h --help --memory-db --maintenance-action --review-status --limit --format" ;;
            memory-review) candidates="-h --help --memory-db --candidate-id --action --operator-ref --evidence-ref --rollback-plan-ref --note --format" ;;
            mission-cycle) candidates="-h --help --mission-id --memory-db --evolution-db --workflow-profile --limit --format" ;;
            operator-dashboard) candidates="-h --help --mission-id --memory-db --evolution-db --workflow-profile --limit --format" ;;
            daily-workspace) candidates="-h --help --memory-db --evolution-db --limit --format" ;;
            operator-outcomes) candidates="-h --help --observability-db --memory-db --period-start --period-end --event-limit --mission-limit --format" ;;
            command-reference) candidates="-h --help --format" ;;
            completion) candidates="-h --help --shell --format" ;;
            readiness-dashboard) candidates="-h --help --run-gate --longitudinal-report --format" ;;
            doctor) candidates="-h --help --runtime-dir --memory-db --evolution-db --observability-db --format" ;;
            learning-report) candidates="-h --help --observability-db --memory-db --evolution-db --limit --minimum-observations --format" ;;
            progress-report) candidates="-h --help --mission-id --session-id --operator-identity-ref --canonical-user-ref --format" ;;
            mission-workflow) candidates="-h --help --session-id --mission-id --evolution-db --operator-identity-ref --canonical-user-ref --format" ;;
            mission-feedback) candidates="-h --help --mission-id --session-id --experience-id --assessment --rating --comment --correction --next-expectation --evidence-ref --evolution-db --operator-identity-ref --canonical-user-ref --format" ;;
        esac
    fi
    COMPREPLY=( $(compgen -W "$candidates" -- "$cur") )
}
complete -F _jarvis_console jarvis-console
