# Generated by JARVIS MB-199. Do not edit.
$JarvisConsoleCommands = @('ask', 'chat', 'objectives', 'goal-strategy', 'objective', 'work-items', 'work-item', 'open-loops', 'resume-loop', 'artifacts', 'artifact', 'technology-candidates', 'experience-reflections', 'procedural-playbooks', 'skill-evolution', 'evolution-review-queue', 'evolution-review', 'memory-review-queue', 'memory-review', 'mission-cycle', 'operator-dashboard', 'daily-workspace', 'operator-outcomes', 'command-reference', 'completion', 'readiness-dashboard', 'doctor', 'learning-report', 'progress-report', 'mission-workflow', 'mission-feedback')
$JarvisConsoleOptions = @{
    'ask' = @('-h', '--help', '--session-id', '--mission-id', '--operator-identity-ref', '--canonical-user-ref', '--debug', '--format')
    'chat' = @('-h', '--help', '--session-id', '--mission-id', '--message', '--operator-identity-ref', '--canonical-user-ref', '--debug', '--format')
    'objectives' = @('-h', '--help', '--mission-id', '--format')
    'goal-strategy' = @('-h', '--help', '--mission-id', '--session-id', '--operator-identity-ref', '--canonical-user-ref', '--format')
    'objective' = @('-h', '--help', '--mission-id', '--session-id', '--action', '--next-action-ref', '--operator-identity-ref', '--canonical-user-ref', '--format')
    'work-items' = @('-h', '--help', '--mission-id', '--format')
    'work-item' = @('-h', '--help', '--mission-id', '--session-id', '--action', '--work-item-ref', '--next-action-ref', '--depends-on', '--clear-dependencies', '--priority', '--blocker-ref', '--operator-identity-ref', '--canonical-user-ref', '--format')
    'open-loops' = @('-h', '--help', '--mission-id', '--format')
    'resume-loop' = @('-h', '--help', '--mission-id', '--open-loop-ref', '--session-id', '--operator-identity-ref', '--canonical-user-ref', '--format')
    'artifacts' = @('-h', '--help', '--mission-id', '--format')
    'artifact' = @('-h', '--help', '--mission-id', '--session-id', '--action', '--artifact-ref', '--artifact-version', '--work-item-ref', '--replacement-artifact-ref', '--rollback-plan-ref', '--operator-identity-ref', '--canonical-user-ref', '--format')
    'technology-candidates' = @('-h', '--help', '--evolution-db', '--limit', '--format')
    'experience-reflections' = @('-h', '--help', '--memory-db', '--mission-id', '--workflow-profile', '--limit', '--format')
    'procedural-playbooks' = @('-h', '--help', '--memory-db', '--workflow-profile', '--review-status', '--limit', '--format')
    'skill-evolution' = @('-h', '--help', '--memory-db', '--evolution-db', '--skill-id', '--version', '--workflow-profile', '--route', '--domain', '--limit', '--format')
    'evolution-review-queue' = @('-h', '--help', '--evolution-db', '--limit', '--format')
    'evolution-review' = @('-h', '--help', '--evolution-db', '--proposal-id', '--action', '--operator-ref', '--evidence-ref', '--proposed-test', '--rollback-plan-ref', '--risk-acceptance', '--note', '--format')
    'memory-review-queue' = @('-h', '--help', '--memory-db', '--maintenance-action', '--review-status', '--limit', '--format')
    'memory-review' = @('-h', '--help', '--memory-db', '--candidate-id', '--action', '--operator-ref', '--evidence-ref', '--rollback-plan-ref', '--note', '--format')
    'mission-cycle' = @('-h', '--help', '--mission-id', '--memory-db', '--evolution-db', '--workflow-profile', '--limit', '--format')
    'operator-dashboard' = @('-h', '--help', '--mission-id', '--memory-db', '--evolution-db', '--workflow-profile', '--limit', '--format')
    'daily-workspace' = @('-h', '--help', '--memory-db', '--evolution-db', '--limit', '--format')
    'operator-outcomes' = @('-h', '--help', '--observability-db', '--memory-db', '--period-start', '--period-end', '--event-limit', '--mission-limit', '--format')
    'command-reference' = @('-h', '--help', '--format')
    'completion' = @('-h', '--help', '--shell', '--format')
    'readiness-dashboard' = @('-h', '--help', '--run-gate', '--longitudinal-report', '--format')
    'doctor' = @('-h', '--help', '--runtime-dir', '--memory-db', '--evolution-db', '--observability-db', '--format')
    'learning-report' = @('-h', '--help', '--observability-db', '--memory-db', '--evolution-db', '--limit', '--minimum-observations', '--format')
    'progress-report' = @('-h', '--help', '--mission-id', '--session-id', '--operator-identity-ref', '--canonical-user-ref', '--format')
    'mission-workflow' = @('-h', '--help', '--session-id', '--mission-id', '--evolution-db', '--operator-identity-ref', '--canonical-user-ref', '--format')
    'mission-feedback' = @('-h', '--help', '--mission-id', '--session-id', '--experience-id', '--assessment', '--rating', '--comment', '--correction', '--next-expectation', '--evidence-ref', '--evolution-db', '--operator-identity-ref', '--canonical-user-ref', '--format')
}
$JarvisConsoleChoices = @{
    'ask|--format' = @('text', 'json')
    'chat|--format' = @('text', 'json')
    'objectives|--format' = @('text', 'json')
    'goal-strategy|--format' = @('text', 'json')
    'objective|--action' = @('resume', 'pause', 'block', 'complete', 'redefine-next-action')
    'objective|--format' = @('text', 'json')
    'work-items|--format' = @('text', 'json')
    'work-item|--action' = @('create', 'update', 'resume', 'pause', 'block', 'complete', 'redefine-next-action')
    'work-item|--priority' = @('p0', 'p1', 'p2', 'p3')
    'work-item|--format' = @('text', 'json')
    'open-loops|--format' = @('text', 'json')
    'resume-loop|--format' = @('text', 'json')
    'artifacts|--format' = @('text', 'json')
    'artifact|--action' = @('register', 'activate', 'archive', 'replace', 'rollback')
    'artifact|--format' = @('text', 'json')
    'technology-candidates|--format' = @('text', 'json')
    'experience-reflections|--format' = @('text', 'json')
    'procedural-playbooks|--format' = @('text', 'json')
    'skill-evolution|--format' = @('text', 'json')
    'evolution-review-queue|--format' = @('text', 'json')
    'evolution-review|--action' = @('approve', 'reject', 'sandbox', 'needs-review', 'rollback')
    'evolution-review|--format' = @('text', 'json')
    'memory-review-queue|--maintenance-action' = @('consolidate', 'archive', 'expire')
    'memory-review-queue|--format' = @('text', 'json')
    'memory-review|--action' = @('approve', 'reject', 'needs-review', 'rollback')
    'memory-review|--format' = @('text', 'json')
    'mission-cycle|--format' = @('text', 'json')
    'operator-dashboard|--format' = @('text', 'json')
    'daily-workspace|--format' = @('text', 'json')
    'operator-outcomes|--format' = @('text', 'json')
    'command-reference|--format' = @('text', 'json')
    'completion|--shell' = @('powershell', 'bash', 'zsh')
    'completion|--format' = @('text', 'json')
    'readiness-dashboard|--run-gate' = @('quick', 'standard')
    'readiness-dashboard|--format' = @('text', 'json')
    'doctor|--format' = @('text', 'json')
    'learning-report|--format' = @('text', 'json')
    'progress-report|--format' = @('text', 'json')
    'mission-workflow|--format' = @('text', 'json')
    'mission-feedback|--assessment' = @('helpful', 'partially-helpful', 'not-helpful', 'correction')
    'mission-feedback|--format' = @('text', 'json')
}
Register-ArgumentCompleter -Native -CommandName jarvis-console -ScriptBlock {
    param($wordToComplete, $commandAst, $cursorPosition)
    $tokens = @($commandAst.CommandElements | ForEach-Object { $_.Extent.Text })
    $command = $tokens | Where-Object { $_ -in $JarvisConsoleCommands } | Select-Object -First 1
    $previous = if ($tokens.Count -gt 1) { $tokens[-2] } else { '' }
    $choiceKey = "$command|$previous"
    if (-not $command -and $previous -eq '--format') {
        $candidates = @('text', 'json')
    } elseif ($JarvisConsoleChoices.ContainsKey($choiceKey)) {
        $candidates = $JarvisConsoleChoices[$choiceKey]
    } elseif ($command) {
        $candidates = $JarvisConsoleOptions[$command]
    } else {
        $candidates = @('--format') + $JarvisConsoleCommands
    }
    $candidates | Where-Object { $_ -like "$wordToComplete*" } | ForEach-Object {
        [System.Management.Automation.CompletionResult]::new($_, $_, 'ParameterValue', $_)
    }
}
