"""Owned loopback TLS fixture: synthetic CA, no Internet or insecure TLS switch."""

from __future__ import annotations

import socket
import ssl
import threading
from contextlib import contextmanager
from datetime import UTC, datetime, timedelta

from cryptography import x509
from cryptography.hazmat.primitives import hashes, serialization
from cryptography.hazmat.primitives.asymmetric import ec
from cryptography.x509.oid import ExtendedKeyUsageOID, NameOID

HOSTNAME = "fixture.example"
PUBLIC_PIN = "8.8.8.8"
URL = f"https://{HOSTNAME}/private%20fixture?token=private-marker"


def response(body=b"fixture", *, headers=None, status=b"200 OK"):
    if headers is None:
        headers = [
            (b"Content-Type", b"text/plain; charset=utf-8"),
            (b"Content-Length", str(len(body)).encode("ascii")),
            (b"Connection", b"close"),
        ]
    return (
        b"HTTP/1.1 "
        + status
        + b"\r\n"
        + b"\r\n".join(key + b": " + value for key, value in headers)
        + b"\r\n\r\n"
        + body
    )


def certificate_contexts(directory, *, hostname=HOSTNAME, expired=False):
    """Certificates generated by cryptography and never read from a human store."""
    now = datetime.now(UTC)
    ca_key = ec.generate_private_key(ec.SECP256R1())
    ca_name = x509.Name([x509.NameAttribute(NameOID.COMMON_NAME, "JARVIS fixture CA")])
    ca = (
        x509.CertificateBuilder()
        .subject_name(ca_name)
        .issuer_name(ca_name)
        .public_key(ca_key.public_key())
        .serial_number(x509.random_serial_number())
        .not_valid_before(now - timedelta(days=1))
        .not_valid_after(now + timedelta(days=2))
        .add_extension(x509.BasicConstraints(ca=True, path_length=0), critical=True)
        .add_extension(
            x509.KeyUsage(True, False, False, False, False, True, True, False, False), critical=True
        )
        .sign(ca_key, hashes.SHA256())
    )
    key = ec.generate_private_key(ec.SECP256R1())
    name = x509.Name([x509.NameAttribute(NameOID.COMMON_NAME, hostname)])
    certificate = (
        x509.CertificateBuilder()
        .subject_name(name)
        .issuer_name(ca_name)
        .public_key(key.public_key())
        .serial_number(x509.random_serial_number())
        .not_valid_before(now - timedelta(days=2))
        .not_valid_after(now - timedelta(days=1) if expired else now + timedelta(days=1))
        .add_extension(x509.BasicConstraints(ca=False, path_length=None), critical=True)
        .add_extension(x509.SubjectAlternativeName([x509.DNSName(hostname)]), critical=False)
        .add_extension(x509.ExtendedKeyUsage([ExtendedKeyUsageOID.SERVER_AUTH]), critical=False)
        .sign(ca_key, hashes.SHA256())
    )
    ca_path, cert_path, key_path = (directory / name for name in ("ca.pem", "cert.pem", "key.pem"))
    ca_path.write_bytes(ca.public_bytes(serialization.Encoding.PEM))
    cert_path.write_bytes(certificate.public_bytes(serialization.Encoding.PEM))
    key_path.write_bytes(
        key.private_bytes(
            serialization.Encoding.PEM,
            serialization.PrivateFormat.PKCS8,
            serialization.NoEncryption(),
        )
    )
    server = ssl.SSLContext(ssl.PROTOCOL_TLS_SERVER)
    server.minimum_version = ssl.TLSVersion.TLSv1_2
    server.load_cert_chain(cert_path, key_path)
    client = ssl.SSLContext(ssl.PROTOCOL_TLS_CLIENT)
    client.load_verify_locations(cafile=str(ca_path))
    client.minimum_version = ssl.TLSVersion.TLSv1_2
    client.keylog_filename = None
    assert client.check_hostname and client.verify_mode == ssl.CERT_REQUIRED
    return server, client


class TlsFixture:
    def __init__(self, context, payload, *, stall_handshake=False, send_parts=None):
        self.context = context
        self.payload = payload
        self.stall_handshake = stall_handshake
        self.send_parts = send_parts
        self.requests = []
        self.server_names = []
        self.connections = []
        self.accepted = threading.Event()
        self.request_received = threading.Event()
        self.response_sent = threading.Event()
        self.stop = threading.Event()
        self.listener = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
        self.listener.bind(("127.0.0.1", 0))
        self.listener.listen(5)
        self.listener.settimeout(0.05)
        self.address = self.listener.getsockname()
        self.context.set_servername_callback(
            lambda _sock, name, _ctx: self.server_names.append(name)
        )
        self.thread = threading.Thread(target=self._serve, daemon=True)

    def _serve(self):
        while not self.stop.is_set():
            try:
                connection, _ = self.listener.accept()
            except socket.timeout:
                continue
            except OSError:
                return
            self.connections.append(connection)
            self.accepted.set()
            try:
                connection.settimeout(0.5)
                if self.stall_handshake:
                    self.stop.wait(2)
                    continue
                connection = self.context.wrap_socket(connection, server_side=True)
                self.connections.append(connection)
                request = bytearray()
                while b"\r\n\r\n" not in request:
                    block = connection.recv(4096)
                    if not block or len(request) > 16384:
                        break
                    request.extend(block)
                self.requests.append(bytes(request))
                self.request_received.set()
                for block, delay in self.send_parts or [(self.payload, 0)]:
                    if self.stop.wait(delay):
                        break
                    connection.sendall(block)
                    self.response_sent.set()
            except (OSError, ValueError):
                pass
            finally:
                connection.close()

    def close(self):
        self.stop.set()
        self.listener.close()
        for connection in self.connections:
            try:
                connection.close()
            except OSError:
                pass
        self.thread.join(timeout=2)
        assert not self.thread.is_alive(), "owned TLS fixture thread did not stop"


@contextmanager
def tls_fixture(directory, payload, **kwargs):
    cert_options = {key: kwargs.pop(key) for key in ("hostname", "expired") if key in kwargs}
    server, client = certificate_contexts(directory, **cert_options)
    fixture = TlsFixture(server, payload, **kwargs)
    fixture.thread.start()
    try:
        yield fixture, client
    finally:
        fixture.close()


def route_owned_fixture(monkeypatch, fixture, client):
    from operational_service.adapters.browser import https_transport

    dials = []

    def dial(pin):
        assert pin == PUBLIC_PIN
        dials.append(pin)
        return fixture.address

    def no_dns(*_args, **_kwargs):
        raise AssertionError("DNS resolution is forbidden in this isolated fixture")

    monkeypatch.setattr(https_transport, "_dial_address", dial)
    monkeypatch.setattr(https_transport, "_client_context", lambda: client)
    monkeypatch.setattr(socket, "getaddrinfo", no_dns)
    return dials
