"""Schema metadata for canonical contracts."""

from dataclasses import dataclass


@dataclass(frozen=True)
class CanonicalSchema:
    """Declarative schema metadata derived from the master document."""

    name: str
    contract_name: str
    required_fields: tuple[str, ...]
    optional_fields: tuple[str, ...] = ()
    notes: tuple[str, ...] = ()
    version: str = "v1"


INPUT_SCHEMA = CanonicalSchema(
    name="InputSchema",
    contract_name="InputContract",
    required_fields=(
        "request_id",
        "session_id",
        "channel",
        "input_type",
        "content",
        "timestamp",
    ),
    optional_fields=(
        "mission_id",
        "user_id",
        "metadata",
        "attachments",
        "locale",
        "priority_hint",
        "surface_id",
        "surface_kind",
        "surface_session_id",
        "surface_capability_scope",
        "operator_identity_ref",
        "canonical_user_ref",
        "surface_continuity_status",
        "project_ref",
        "objective_ref",
        "work_item_refs",
        "checkpoint_refs",
        "artifact_refs",
        "objective_status",
        "next_action_ref",
        "requested_autonomy_level",
        "max_autonomy_level",
        "autonomy_confirmation_mode",
        "autonomy_policy_refs",
    ),
)

AUTONOMY_LADDER_SCHEMA = CanonicalSchema(
    name="AutonomyLadderSchema",
    contract_name="AutonomyLadderContract",
    required_fields=(
        "requested_autonomy_level",
        "max_autonomy_level",
        "effective_autonomy_level",
        "autonomy_ladder_status",
        "max_capability_mode",
        "human_confirmation_required",
        "human_confirmation_mode",
    ),
    optional_fields=(
        "allowed_runtime_actions",
        "blocked_runtime_actions",
        "policy_refs",
        "summary",
        "automatic_promotion_allowed",
        "core_mutation_allowed",
    ),
    notes=(
        "Runtime autonomy declaration only; enforcement belongs to governance.",
        "No autonomy level grants automatic promotion or core mutation.",
    ),
)

SURFACE_IDENTITY_SCHEMA = CanonicalSchema(
    name="SurfaceIdentitySchema",
    contract_name="SurfaceIdentityContract",
    required_fields=(
        "surface_id",
        "surface_kind",
        "surface_session_id",
    ),
    optional_fields=(
        "surface_capability_scope",
        "operator_identity_ref",
        "canonical_user_ref",
        "surface_continuity_status",
    ),
    notes=(
        "Minimum sovereign surface identity contract for bounded multisurface continuity.",
    ),
)

PROJECT_OBJECTIVE_CONTINUITY_SCHEMA = CanonicalSchema(
    name="ProjectObjectiveContinuitySchema",
    contract_name="ProjectObjectiveContinuityContract",
    required_fields=(),
    optional_fields=(
        "project_ref",
        "objective_ref",
        "work_item_refs",
        "checkpoint_refs",
        "artifact_refs",
        "objective_status",
        "next_action_ref",
    ),
    notes=(
        "Minimum governed project/objective continuity contract; "
        "not a scheduler or autonomous executor.",
    ),
)

LONG_HORIZON_GOAL_STRATEGY_SCHEMA = CanonicalSchema(
    name="LongHorizonGoalStrategySchema",
    contract_name="LongHorizonGoalStrategyContract",
    required_fields=(
        "mission_id",
        "strategy_status",
        "strategy_summary",
    ),
    optional_fields=(
        "milestone_refs",
        "risk_refs",
        "memory_anchor_refs",
        "next_action_ref",
        "evidence_refs",
        "memory_write_mode",
        "autonomous_scheduling_allowed",
        "generated_from_state_refs",
    ),
    notes=(
        "Read-only long-horizon strategy view derived from mission state; "
        "not a scheduler or autonomous execution permit.",
    ),
)

MISSION_PROGRESS_REPORT_SCHEMA = CanonicalSchema(
    name="MissionProgressReportSchema",
    contract_name="MissionProgressReportContract",
    required_fields=(
        "report_id",
        "mission_id",
        "report_status",
        "progress_summary",
        "report_text",
        "mission_goal",
        "mission_status",
        "objective_status",
        "generated_at",
    ),
    optional_fields=(
        "work_item_refs",
        "active_work_items",
        "artifact_refs",
        "open_checkpoint_refs",
        "milestone_refs",
        "risk_refs",
        "memory_influence_refs",
        "learning_refs",
        "evidence_refs",
        "pending_decisions",
        "latest_experience_id",
        "latest_experience_outcome",
        "latest_reflection_id",
        "latest_reflection_status",
        "operator_usefulness_status",
        "next_action_ref",
        "memory_write_mode",
        "autonomous_execution_allowed",
    ),
    notes=(
        "Read-only human progress report derived from canonical mission state.",
    ),
)

TECHNOLOGY_ABSORPTION_CANDIDATE_SCHEMA = CanonicalSchema(
    name="TechnologyAbsorptionCandidateSchema",
    contract_name="TechnologyAbsorptionCandidateContract",
    required_fields=(
        "candidate_ref",
        "technology_name",
        "absorption_class",
        "target_gap_refs",
        "hypothesis",
        "expected_gain",
    ),
    optional_fields=(
        "source_refs",
        "evidence_refs",
        "proposed_tests",
        "risk_hint",
        "status",
        "decision",
        "requested_core_role",
        "sandbox_required",
        "human_review_required",
        "rollback_plan_ref",
        "blockers",
    ),
    notes=(
        "External technology enters first as reference, experiment or controlled "
        "complement; promotion is manual and evidence-bound.",
    ),
)

EXPERIENCE_RECORD_SCHEMA = CanonicalSchema(
    name="ExperienceRecordSchema",
    contract_name="ExperienceRecordContract",
    required_fields=(
        "experience_id",
        "mission_id",
        "workflow_profile",
        "outcome_status",
        "timestamp",
    ),
    optional_fields=(
        "user_intent",
        "route",
        "primary_mind",
        "primary_domain_driver",
        "specialist_used",
        "plan_summary",
        "execution_summary",
        "outcome",
        "errors",
        "tools_used",
        "checkpoints",
        "user_feedback",
        "objective_ref",
        "surface_id",
        "evidence_refs",
        "signal_refs",
        "failure_modes",
        "decision_refs",
        "learned_patterns",
        "next_action_ref",
        "source_kind",
        "reusable_memory_status",
        "human_review_required",
        "automatic_promotion_allowed",
        "core_mutation_allowed",
    ),
    notes=(
        "Bounded operational experience record; not a self-modification permit.",
    ),
)

POST_TASK_REFLECTION_SCHEMA = CanonicalSchema(
    name="PostTaskReflectionSchema",
    contract_name="PostTaskReflectionContract",
    required_fields=(
        "reflection_id",
        "experience_id",
        "reflection_status",
        "learning_candidate",
        "recommendation",
        "timestamp",
    ),
    optional_fields=(
        "proposed_change_type",
        "evidence_refs",
        "proposed_tests",
        "blockers",
        "rollback_plan_ref",
        "risk_hint",
        "human_review_required",
        "automatic_promotion_allowed",
        "core_mutation_allowed",
    ),
    notes=(
        "Post-task reflection feeds sandbox proposals and manual review only.",
    ),
)

OPERATOR_FEEDBACK_SCHEMA = CanonicalSchema(
    name="OperatorFeedbackSchema",
    contract_name="OperatorFeedbackContract",
    required_fields=(
        "feedback_id",
        "mission_id",
        "experience_id",
        "assessment",
        "operator_ref",
        "timestamp",
    ),
    optional_fields=(
        "rating",
        "comment",
        "correction",
        "next_expectation",
        "evidence_refs",
        "feedback_status",
        "evolution_review_status",
        "memory_write_mode",
        "human_review_required",
        "automatic_promotion_allowed",
        "core_mutation_allowed",
    ),
    notes=(
        "Explicit bounded operator feedback enriches experience and reflection; "
        "it never authorizes promotion or core mutation.",
    ),
)

RECURRING_PATTERN_EVIDENCE_SCHEMA = CanonicalSchema(
    name="RecurringPatternEvidenceSchema",
    contract_name="RecurringPatternEvidenceContract",
    required_fields=(
        "pattern_id",
        "pattern_type",
        "pattern_status",
        "workflow_profile",
        "route",
        "domain",
        "occurrence_count",
        "minimum_occurrences",
        "successful_occurrences",
        "non_successful_occurrences",
        "confidence_status",
        "outcome_summary",
        "pattern_summary",
        "experience_refs",
        "reflection_refs",
        "feedback_refs",
        "evidence_refs",
        "recurring_signals",
        "conflict_flags",
        "blockers",
        "generated_at",
    ),
    optional_fields=(
        "human_review_required",
        "skill_candidate_generation_allowed",
        "automatic_skill_creation_allowed",
        "automatic_promotion_allowed",
        "core_mutation_allowed",
    ),
    notes=(
        "Bounded recurrence evidence only; it cannot create or activate a skill.",
    ),
)

RECURRING_PATTERN_REPORT_SCHEMA = CanonicalSchema(
    name="RecurringPatternReportSchema",
    contract_name="RecurringPatternReportContract",
    required_fields=(
        "report_id",
        "report_status",
        "records_analyzed",
        "compatible_group_count",
        "eligible_pattern_count",
        "minimum_occurrences",
        "scope_filters",
        "patterns",
        "evidence_refs",
        "blockers",
        "generated_at",
    ),
    optional_fields=(
        "sample_truncated",
        "read_only",
        "human_review_required",
        "skill_candidate_generation_allowed",
        "automatic_skill_creation_allowed",
        "automatic_promotion_allowed",
        "core_mutation_allowed",
    ),
    notes=(
        "Read-only recurring-pattern report over compatible experience scopes.",
    ),
)

SKILL_CANDIDATE_SCHEMA = CanonicalSchema(
    name="SkillCandidateSchema",
    contract_name="SkillCandidateContract",
    required_fields=(
        "skill_candidate_id",
        "skill_id",
        "skill_name",
        "version",
        "workflow_profile",
        "domain",
        "specialist_type",
        "inputs",
        "outputs",
        "allowed_tools",
        "bounded_instructions",
        "risk_level",
        "evidence_refs",
        "source_pattern_refs",
        "failure_modes",
        "proposed_tests",
        "rollback_plan_ref",
        "timestamp",
    ),
    optional_fields=(
        "registry_status",
        "review_status",
        "activation_status",
        "blockers",
        "sandbox_required",
        "human_review_required",
        "automatic_activation_allowed",
        "automatic_promotion_allowed",
        "core_mutation_allowed",
        "memory_write_mode",
    ),
    notes=(
        "Versioned inactive skill candidate; registration is not activation or promotion.",
    ),
)

SKILL_MINING_REQUEST_SCHEMA = CanonicalSchema(
    name="SkillMiningRequestSchema",
    contract_name="SkillMiningRequestContract",
    required_fields=(
        "mining_request_id",
        "source_pattern_ref",
        "skill_id",
        "skill_name",
        "version",
        "specialist_type",
        "inputs",
        "outputs",
        "allowed_tools",
        "bounded_instructions",
        "risk_level",
        "failure_modes",
        "proposed_tests",
        "rollback_plan_ref",
        "timestamp",
    ),
    optional_fields=(
        "human_review_required",
        "automatic_mining_allowed",
        "automatic_activation_allowed",
        "automatic_promotion_allowed",
        "core_mutation_allowed",
    ),
    notes=(
        "Bounded explicit mining specification; it grants no runtime authority.",
    ),
)

SKILL_MINING_RESULT_SCHEMA = CanonicalSchema(
    name="SkillMiningResultSchema",
    contract_name="SkillMiningResultContract",
    required_fields=(
        "mining_result_id",
        "mining_status",
        "eligibility_status",
        "source_pattern_ref",
        "source_authority_status",
        "threshold_occurrences",
        "observed_occurrences",
        "blockers",
        "evidence_refs",
        "generated_at",
    ),
    optional_fields=(
        "candidate",
        "human_review_required",
        "automatic_activation_allowed",
        "automatic_promotion_allowed",
        "core_mutation_allowed",
    ),
    notes=(
        "Blocked mining returns no candidate; successful mining remains inactive.",
    ),
)

SKILL_SANDBOX_CASE_RESULT_SCHEMA = CanonicalSchema(
    name="SkillSandboxCaseResultSchema",
    contract_name="SkillSandboxCaseResultContract",
    required_fields=(
        "case_id",
        "passed",
        "checks",
        "failed_checks",
        "evidence_refs",
    ),
    notes=("Case pass status is derived from all declared checks.",),
)

SKILL_SANDBOX_EVAL_SCHEMA = CanonicalSchema(
    name="SkillSandboxEvalSchema",
    contract_name="SkillSandboxEvalContract",
    required_fields=(
        "eval_id",
        "skill_candidate_id",
        "skill_id",
        "version",
        "evolution_proposal_id",
        "review_decision_id",
        "eval_status",
        "required_pass_rate",
        "pass_rate",
        "total_cases",
        "passed_cases",
        "failed_cases",
        "case_results",
        "evidence_refs",
        "proposed_tests",
        "rollback_plan_ref",
        "blockers",
        "generated_at",
    ),
    optional_fields=(
        "sandbox_only",
        "human_review_required",
        "runtime_activation_allowed",
        "promotion_authorized",
        "automatic_promotion_allowed",
        "core_mutation_allowed",
    ),
    notes=(
        "Sandbox evidence only; a passing eval remains pending release and human gates.",
    ),
)

SKILL_EVOLUTION_OPERATOR_ITEM_SCHEMA = CanonicalSchema(
    name="SkillEvolutionOperatorItemSchema",
    contract_name="SkillEvolutionOperatorItemContract",
    required_fields=(
        "skill_candidate_id",
        "skill_id",
        "skill_name",
        "version",
        "workflow_profile",
        "route",
        "domain",
        "specialist_type",
        "risk_level",
        "registry_status",
        "review_status",
        "activation_status",
        "evolution_status",
        "source_pattern_refs",
        "pattern_status",
        "pattern_summary",
        "occurrence_count",
        "minimum_occurrences",
        "confidence_status",
        "proposal_id",
        "proposal_status",
        "sandbox_eval_ref",
        "sandbox_eval_status",
        "sandbox_pass_rate",
        "allowed_tools",
        "evidence_refs",
        "proposed_tests",
        "rollback_plan_ref",
        "blockers",
        "next_operator_action",
    ),
    optional_fields=(
        "read_only",
        "human_review_required",
        "runtime_activation_allowed",
        "promotion_authorized",
        "automatic_promotion_allowed",
        "core_mutation_allowed",
    ),
    notes=(
        "Read-only correlated skill evolution item; it grants no runtime authority.",
    ),
)

SKILL_EVOLUTION_OPERATOR_VIEW_SCHEMA = CanonicalSchema(
    name="SkillEvolutionOperatorViewSchema",
    contract_name="SkillEvolutionOperatorViewContract",
    required_fields=(
        "view_id",
        "view_status",
        "pattern_report_id",
        "pattern_report_status",
        "pattern_count",
        "candidate_count",
        "items",
        "unregistered_pattern_refs",
        "blockers",
        "generated_at",
    ),
    optional_fields=(
        "read_only",
        "human_review_required",
        "runtime_activation_allowed",
        "promotion_authorized",
        "automatic_promotion_allowed",
        "core_mutation_allowed",
    ),
    notes=(
        "Operator projection only; human review and release gates remain mandatory.",
    ),
)

WORKFLOW_PROFILE_VERSION_SCHEMA = CanonicalSchema(
    name="WorkflowProfileVersionSchema",
    contract_name="WorkflowProfileVersionContract",
    required_fields=(
        "workflow_version_id",
        "workflow_profile",
        "version",
        "route",
        "lifecycle_status",
        "definition_hash",
        "workflow_steps",
        "workflow_checkpoints",
        "workflow_decision_points",
        "success_criteria",
        "evidence_refs",
        "proposed_tests",
        "rollback_plan_ref",
        "source_registry_ref",
        "source_registry_fingerprint",
        "timestamp",
    ),
    optional_fields=(
        "baseline_version_ref",
        "change_summary",
        "risk_level",
        "review_status",
        "runtime_binding_status",
        "blockers",
        "human_review_required",
        "sandbox_required",
        "active_registry_write_allowed",
        "runtime_activation_allowed",
        "automatic_promotion_allowed",
        "core_mutation_allowed",
    ),
    notes=(
        "Version snapshot or inactive candidate; it cannot mutate the active registry.",
    ),
)

WORKFLOW_PROFILE_VERSION_REGISTRY_SCHEMA = CanonicalSchema(
    name="WorkflowProfileVersionRegistrySchema",
    contract_name="WorkflowProfileVersionRegistryContract",
    required_fields=(
        "registry_id",
        "registry_version",
        "registry_status",
        "active_registry_ref",
        "active_registry_fingerprint",
        "workflow_count",
        "baseline_count",
        "candidate_count",
        "versions",
        "evidence_refs",
        "blockers",
        "generated_at",
    ),
    optional_fields=(
        "read_only",
        "human_review_required",
        "active_registry_mutation_allowed",
        "runtime_activation_allowed",
        "automatic_promotion_allowed",
        "core_mutation_allowed",
    ),
    notes=(
        "Immutable side registry over the sovereign active workflow registry.",
    ),
)

WORKFLOW_EVOLUTION_REQUEST_SCHEMA = CanonicalSchema(
    name="WorkflowEvolutionRequestSchema",
    contract_name="WorkflowEvolutionRequestContract",
    required_fields=(
        "workflow_evolution_request_id",
        "source_pattern_ref",
        "source_review_decision_id",
        "baseline_version_ref",
        "candidate_version",
        "change_summary",
        "evidence_refs",
        "proposed_tests",
        "rollback_plan_ref",
        "risk_level",
        "timestamp",
    ),
    optional_fields=(
        "step_additions",
        "step_removals",
        "checkpoint_additions",
        "checkpoint_removals",
        "decision_point_additions",
        "decision_point_removals",
        "success_criteria_additions",
        "success_criteria_removals",
        "human_review_required",
        "automatic_build_allowed",
        "active_registry_write_allowed",
        "runtime_activation_allowed",
        "automatic_promotion_allowed",
        "core_mutation_allowed",
    ),
    notes=(
        "Explicit reviewed workflow delta; it grants no registry or runtime authority.",
    ),
)

WORKFLOW_EVOLUTION_BUILD_RESULT_SCHEMA = CanonicalSchema(
    name="WorkflowEvolutionBuildResultSchema",
    contract_name="WorkflowEvolutionBuildResultContract",
    required_fields=(
        "workflow_evolution_result_id",
        "build_status",
        "source_pattern_ref",
        "source_review_decision_id",
        "baseline_version_ref",
        "source_authority_status",
        "delta_summary",
        "evidence_refs",
        "generated_at",
    ),
    optional_fields=(
        "candidate",
        "blockers",
        "human_review_required",
        "active_registry_write_allowed",
        "runtime_activation_allowed",
        "automatic_promotion_allowed",
        "core_mutation_allowed",
    ),
    notes=(
        "Blocked builds return no candidate; successful candidates remain inactive "
        "and review-bound.",
    ),
)

WORKFLOW_VARIANT_EVAL_CASE_SCHEMA = CanonicalSchema(
    name="WorkflowVariantEvalCaseSchema",
    contract_name="WorkflowVariantEvalCaseContract",
    required_fields=(
        "case_id",
        "scenario_ref",
        "workflow_profile",
        "route",
        "baseline_version_ref",
        "candidate_version_ref",
        "baseline_metrics",
        "candidate_metrics",
        "evidence_refs",
    ),
    optional_fields=(
        "required_candidate_steps",
        "required_candidate_checkpoints",
        "required_candidate_decision_points",
        "required_candidate_success_criteria",
        "offline_only",
        "human_review_required",
        "promotion_authorized",
        "automatic_promotion_allowed",
        "core_mutation_allowed",
    ),
    notes=(
        "Equivalent offline evidence for one baseline/candidate workflow scenario.",
    ),
)

WORKFLOW_VARIANT_EVAL_CASE_RESULT_SCHEMA = CanonicalSchema(
    name="WorkflowVariantEvalCaseResultSchema",
    contract_name="WorkflowVariantEvalCaseResultContract",
    required_fields=(
        "case_id",
        "scenario_ref",
        "workflow_profile",
        "route",
        "baseline_version_ref",
        "candidate_version_ref",
        "passed",
        "checks",
        "baseline_metrics",
        "candidate_metrics",
        "metric_deltas",
        "improvement_signals",
        "evidence_refs",
    ),
    optional_fields=(
        "regression_flags",
        "failures",
        "offline_only",
        "promotion_authorized",
    ),
    notes=(
        "Per-case comparison evidence; pass status never authorizes promotion.",
    ),
)

WORKFLOW_VARIANT_EVAL_RUN_SCHEMA = CanonicalSchema(
    name="WorkflowVariantEvalRunSchema",
    contract_name="WorkflowVariantEvalRunContract",
    required_fields=(
        "run_id",
        "workflow_profile",
        "route",
        "baseline_version_ref",
        "candidate_version_ref",
        "status",
        "readiness_status",
        "promotion_readiness",
        "comparison_conclusion",
        "pass_rate",
        "total_cases",
        "passed_cases",
        "failed_cases",
        "aggregate_baseline_metrics",
        "aggregate_candidate_metrics",
        "aggregate_metric_deltas",
        "case_results",
        "evidence_refs",
        "generated_at",
    ),
    optional_fields=(
        "regression_flags",
        "blockers",
        "offline_only",
        "human_review_required",
        "promotion_authorized",
        "automatic_promotion_allowed",
        "core_mutation_allowed",
    ),
    notes=(
        "A green workflow eval is manual gate evidence, never promotion authority.",
    ),
)

PROCEDURAL_PLAYBOOK_CANDIDATE_SCHEMA = CanonicalSchema(
    name="ProceduralPlaybookCandidateSchema",
    contract_name="ProceduralPlaybookCandidateContract",
    required_fields=(
        "playbook_candidate_id",
        "procedure_name",
        "workflow_profile",
        "bounded_steps",
        "evidence_refs",
        "timestamp",
    ),
    optional_fields=(
        "route",
        "domain",
        "source_artifact_refs",
        "source_reflection_refs",
        "proposed_tests",
        "rollback_plan_ref",
        "risk_hint",
        "review_status",
        "blockers",
        "human_review_required",
        "automatic_promotion_allowed",
        "core_mutation_allowed",
        "memory_write_mode",
    ),
    notes=(
        "Bounded procedural playbook candidate; never an active rule without "
        "human review and release gate.",
    ),
)

DOMAIN_KNOWLEDGE_PACK_SCHEMA = CanonicalSchema(
    name="DomainKnowledgePackSchema",
    contract_name="DomainKnowledgePackContract",
    required_fields=(
        "knowledge_pack_id",
        "version",
        "canonical_domain_refs",
        "source_refs",
        "content_refs",
        "coverage_topics",
        "evidence_refs",
        "timestamp",
    ),
    optional_fields=(
        "pack_status",
        "freshness_status",
        "review_status",
        "human_review_required",
        "automatic_activation_allowed",
        "core_mutation_allowed",
    ),
    notes=(
        "Versioned candidate knowledge pack; it cannot activate a runtime route by itself.",
    ),
)

DOMAIN_ONBOARDING_CANDIDATE_SCHEMA = CanonicalSchema(
    name="DomainOnboardingCandidateSchema",
    contract_name="DomainOnboardingCandidateContract",
    required_fields=(
        "onboarding_candidate_id",
        "route_name",
        "display_name",
        "canonical_domain_refs",
        "knowledge_pack_id",
        "onboarding_workflow_profile",
        "runtime_workflow_profile",
        "workflow_steps",
        "workflow_checkpoints",
        "workflow_decision_points",
        "proposed_tests",
        "eval_pack_ref",
        "rollback_plan_ref",
        "evidence_refs",
        "timestamp",
    ),
    optional_fields=(
        "linked_specialist_type",
        "specialist_mode",
        "requested_maturity",
        "activation_stage",
        "human_review_required",
        "registry_write_allowed",
        "specialist_promotion_allowed",
        "automatic_activation_allowed",
        "automatic_promotion_allowed",
        "core_mutation_allowed",
    ),
    notes=(
        "Bounded domain onboarding candidate; assessment never writes to active registries.",
    ),
)

DOMAIN_ONBOARDING_ASSESSMENT_SCHEMA = CanonicalSchema(
    name="DomainOnboardingAssessmentSchema",
    contract_name="DomainOnboardingAssessmentContract",
    required_fields=(
        "assessment_id",
        "onboarding_candidate_id",
        "route_name",
        "knowledge_pack_id",
        "readiness_status",
        "decision",
        "criteria",
        "registry_preview",
        "timestamp",
    ),
    optional_fields=(
        "blockers",
        "warnings",
        "human_review_required",
        "registry_write_allowed",
        "specialist_promotion_allowed",
        "automatic_activation_allowed",
        "automatic_promotion_allowed",
        "core_mutation_allowed",
    ),
    notes=(
        "Assessment is advisory and human-review-bound; it is not a promotion permit.",
    ),
)

DOMAIN_EVAL_PACK_SCHEMA = CanonicalSchema(
    name="DomainEvalPackSchema",
    contract_name="DomainEvalPackContract",
    required_fields=(
        "eval_pack_id",
        "version",
        "route_name",
        "canonical_domain_refs",
        "workflow_profile",
        "specialist_type",
        "cases",
        "evidence_refs",
        "timestamp",
    ),
    optional_fields=(
        "minimum_pass_rate",
        "offline_only",
        "human_review_required",
        "automatic_promotion_allowed",
        "core_mutation_allowed",
    ),
    notes=(
        "Versioned offline eval pack for a governed promoted route/domain.",
    ),
)

DOMAIN_EVAL_RUN_SCHEMA = CanonicalSchema(
    name="DomainEvalRunSchema",
    contract_name="DomainEvalRunContract",
    required_fields=(
        "run_id",
        "eval_pack_id",
        "pack_version",
        "route_name",
        "status",
        "readiness_status",
        "promotion_readiness",
        "pass_rate",
        "total_cases",
        "case_results",
        "evidence_refs",
        "generated_at",
    ),
    optional_fields=(
        "passed_cases",
        "failed_cases",
        "blockers",
        "offline_only",
        "human_review_required",
        "promotion_authorized",
        "automatic_promotion_allowed",
        "core_mutation_allowed",
    ),
    notes=(
        "A passing run is evidence for human review, never a promotion authorization.",
    ),
)

KNOWLEDGE_SOURCE_EVIDENCE_SCHEMA = CanonicalSchema(
    name="KnowledgeSourceEvidenceSchema",
    contract_name="KnowledgeSourceEvidenceContract",
    required_fields=(
        "source_ref",
        "domain_name",
        "source_kind",
        "retrieved_at",
        "provenance_status",
        "freshness_status",
        "conflict_status",
    ),
    optional_fields=(
        "confidence_status",
        "published_at",
        "reviewed_at",
        "valid_until",
        "conflict_refs",
        "uncertainty_notes",
    ),
    notes=(
        "Per-source evidence metadata; unknown or missing provenance must remain explicit.",
    ),
)

KNOWLEDGE_EVIDENCE_GOVERNANCE_SCHEMA = CanonicalSchema(
    name="KnowledgeEvidenceGovernanceSchema",
    contract_name="KnowledgeEvidenceGovernanceContract",
    required_fields=(
        "assessment_id",
        "status",
        "use_mode",
        "provenance_status",
        "freshness_status",
        "conflict_status",
        "source_refs",
        "conditions",
        "blockers",
        "uncertainty_notes",
        "timestamp",
    ),
    optional_fields=(
        "human_review_required",
        "request_decision_mutation_allowed",
        "automatic_promotion_allowed",
        "core_mutation_allowed",
    ),
    notes=(
        "Qualifies knowledge use without mutating the request permission decision.",
    ),
)

CAPABILITY_READINESS_SCHEMA = CanonicalSchema(
    name="CapabilityReadinessSchema",
    contract_name="CapabilityReadinessContract",
    required_fields=(
        "capability_id",
        "capability_name",
        "source_status",
        "scope_status",
        "readiness_status",
        "score",
        "target",
        "dependencies",
        "next_slice",
        "evidence_refs",
    ),
    optional_fields=("blockers",),
    notes=(
        "Read-only projection of one capability from the implementation master map.",
    ),
)

REGRESSION_READINESS_REPORT_SCHEMA = CanonicalSchema(
    name="RegressionReadinessReportSchema",
    contract_name="RegressionReadinessReportContract",
    required_fields=(
        "report_id",
        "status",
        "overall_score",
        "capability_counts",
        "capability_results",
        "gate_mode",
        "gate_status",
        "test_status",
        "document_status",
        "backlog_status",
        "status_drift",
        "blockers",
        "warnings",
        "evidence_refs",
        "generated_at",
    ),
    optional_fields=(
        "next_ready_item",
        "read_only",
        "autonomous_release_allowed",
    ),
    notes=(
        "Aggregates existing readiness signals; it never authorizes release autonomously.",
    ),
)

EVOLUTION_REVIEW_QUEUE_ITEM_SCHEMA = CanonicalSchema(
    name="EvolutionReviewQueueItemSchema",
    contract_name="EvolutionReviewQueueItemContract",
    required_fields=(
        "review_item_id",
        "evolution_proposal_id",
        "proposal_type",
        "review_status",
        "review_reason",
        "requires_human_review",
        "requires_sandbox",
    ),
    optional_fields=(
        "risk_hint",
        "target_scope",
        "candidate_refs",
        "blockers",
        "proposed_tests",
        "rollback_plan_ref",
    ),
    notes=(
        "Human review queue view over sandbox evolution proposals; not a promotion permit.",
    ),
)

EVOLUTION_REVIEW_DECISION_SCHEMA = CanonicalSchema(
    name="EvolutionReviewDecisionSchema",
    contract_name="EvolutionReviewDecisionContract",
    required_fields=(
        "review_decision_id",
        "evolution_proposal_id",
        "review_status",
        "decision",
        "operator_ref",
        "timestamp",
    ),
    optional_fields=(
        "evidence_refs",
        "proposed_tests",
        "rollback_plan_ref",
        "risk_acceptance",
        "review_notes",
        "candidate_identity_ref",
        "candidate_version",
        "automatic_promotion_allowed",
        "core_mutation_allowed",
    ),
    notes=(
        "Human evolution review decision; does not authorize automatic promotion.",
    ),
)

REVIEWED_LEARNING_GUIDANCE_SCHEMA = CanonicalSchema(
    name="ReviewedLearningGuidanceSchema",
    contract_name="ReviewedLearningGuidanceContract",
    required_fields=(
        "guidance_id",
        "source_review_decision_id",
        "evolution_proposal_id",
        "review_status",
        "route",
        "workflow_profile",
        "domain",
        "guidance_summary",
        "allowed_usage",
        "evidence_refs",
        "rollback_plan_ref",
        "timestamp",
    ),
    optional_fields=(
        "expires_at",
        "automatic_promotion_allowed",
        "core_mutation_allowed",
    ),
    notes=(
        "Human-reviewed learning guidance for bounded planning/synthesis use; "
        "not a promotion permit.",
    ),
)

MEMORY_RECOVERY_SCHEMA = CanonicalSchema(
    name="MemoryRecoverySchema",
    contract_name="MemoryRecoveryContract",
    required_fields=(
        "memory_query_id",
        "recovery_type",
        "session_id",
        "requested_scopes",
        "context_window",
    ),
    optional_fields=(
        "mission_id",
        "user_id",
        "domain_hints",
        "priority_rules",
        "max_items",
        "sensitivity_ceiling",
    ),
)

MEMORY_RECORD_SCHEMA = CanonicalSchema(
    name="MemoryRecordSchema",
    contract_name="MemoryRecordContract",
    required_fields=(
        "memory_record_id",
        "record_type",
        "source_service",
        "payload",
        "timestamp",
    ),
    optional_fields=(
        "session_id",
        "mission_id",
        "user_id",
        "proposed_memory_class",
        "sensitivity_hint",
        "stability_hint",
        "domain_hint",
        "promotion_candidate",
    ),
)

GOVERNANCE_CHECK_SCHEMA = CanonicalSchema(
    name="GovernanceCheckSchema",
    contract_name="GovernanceCheckContract",
    required_fields=(
        "governance_check_id",
        "subject_type",
        "subject_action",
        "scope",
        "context",
        "sensitivity",
        "reversibility",
    ),
    optional_fields=(
        "mission_id",
        "session_id",
        "proposed_effect",
        "risk_hint",
        "policy_hint",
        "requested_by_service",
        "artifact_refs",
        "decision_frame",
        "mission_continuity_hint",
        "open_loops",
    ),
)

GOVERNANCE_DECISION_SCHEMA = CanonicalSchema(
    name="GovernanceDecisionSchema",
    contract_name="GovernanceDecisionContract",
    required_fields=(
        "decision_id",
        "governance_check_id",
        "risk_level",
        "decision",
        "justification",
        "timestamp",
    ),
    optional_fields=(
        "conditions",
        "requires_audit",
        "requires_rollback_plan",
        "containment_hint",
        "policy_refs",
    ),
)

OPERATION_DISPATCH_SCHEMA = CanonicalSchema(
    name="OperationDispatchSchema",
    contract_name="OperationDispatchContract",
    required_fields=(
        "operation_id",
        "request_id",
        "task_type",
        "task_goal",
        "task_plan",
        "constraints",
        "expected_output",
    ),
    optional_fields=(
        "session_id",
        "mission_id",
        "risk_hint",
        "domain_hints",
        "tool_hints",
        "deadline_hint",
        "priority_hint",
        "artifact_destination",
        "capability_decision_status",
        "capability_decision_objective",
        "capability_decision_reason",
        "capability_decision_selected_mode",
        "capability_decision_authorization_status",
        "capability_decision_fallback_mode",
        "capability_decision_tool_class",
        "capability_decision_handoff_mode",
        "capability_decision_eligible_capabilities",
        "capability_decision_selected_capabilities",
        "request_identity_status",
        "request_active_mission",
        "request_executive_posture",
        "request_authority_level",
        "request_risk_profile",
        "request_reversibility_mode",
        "request_confirmation_mode",
        "request_identity_summary",
        "request_identity_policy_refs",
        "requested_autonomy_level",
        "max_autonomy_level",
        "effective_autonomy_level",
        "autonomy_ladder_status",
        "max_autonomy_capability_mode",
        "autonomy_human_confirmation_required",
        "autonomy_confirmation_mode",
        "autonomy_allowed_runtime_actions",
        "autonomy_blocked_runtime_actions",
        "autonomy_policy_refs",
        "autonomy_summary",
        "autonomy_automatic_promotion_allowed",
        "autonomy_core_mutation_allowed",
        "adaptive_intervention_status",
        "adaptive_intervention_reason",
        "adaptive_intervention_trigger",
        "adaptive_intervention_selected_action",
        "adaptive_intervention_expected_effect",
        "adaptive_intervention_effects",
        "ecosystem_state_status",
        "active_work_items",
        "active_artifact_refs",
        "open_checkpoint_refs",
        "surface_presence",
        "ecosystem_state_summary",
        "surface_id",
        "surface_kind",
        "surface_session_id",
        "surface_capability_scope",
        "operator_identity_ref",
        "canonical_user_ref",
        "surface_continuity_status",
        "project_ref",
        "objective_ref",
        "work_item_refs",
        "checkpoint_refs",
        "artifact_refs",
        "objective_status",
        "next_action_ref",
    ),
)

OPERATION_RESULT_SCHEMA = CanonicalSchema(
    name="OperationResultSchema",
    contract_name="OperationResultContract",
    required_fields=("operation_id", "status", "outputs", "timestamp"),
    optional_fields=(
        "artifacts",
        "errors",
        "checkpoints",
        "ecosystem_state_status",
        "active_work_items",
        "active_artifact_refs",
        "open_checkpoint_refs",
        "surface_presence",
        "ecosystem_state_summary",
        "surface_id",
        "surface_kind",
        "surface_session_id",
        "surface_capability_scope",
        "operator_identity_ref",
        "canonical_user_ref",
        "surface_continuity_status",
        "project_ref",
        "objective_ref",
        "work_item_refs",
        "checkpoint_refs",
        "artifact_refs",
        "objective_status",
        "next_action_ref",
        "next_recommendation",
        "governance_flags",
        "memory_record_hints",
    ),
)

DELIBERATIVE_PLAN_SCHEMA = CanonicalSchema(
    name="DeliberativePlanSchema",
    contract_name="DeliberativePlanContract",
    required_fields=(
        "plan_summary",
        "goal",
        "steps",
        "active_domains",
        "active_minds",
        "constraints",
        "risks",
        "recommended_task_type",
        "rationale",
        "success_criteria",
    ),
    optional_fields=(
        "canonical_domains",
        "primary_canonical_domain",
        "primary_mind",
        "primary_mind_family",
        "primary_domain_driver",
        "arbitration_source",
        "primary_route",
        "mind_domain_specialist_contract_status",
        "mind_domain_specialist_contract_summary",
        "mind_domain_specialist_contract_chain",
        "mind_domain_specialist_active_specialist",
        "mind_domain_specialist_override_mode",
        "mind_domain_specialist_fallback_mode",
        "route_consumer_profile",
        "route_consumer_objective",
        "route_expected_deliverables",
        "route_telemetry_focus",
        "route_workflow_profile",
        "route_workflow_steps",
        "route_workflow_checkpoints",
        "route_workflow_decision_points",
        "tensions_considered",
        "specialist_hints",
        "specialist_resolution_summary",
        "dominant_tension",
        "smallest_safe_next_action",
        "metacognitive_guidance_applied",
        "metacognitive_guidance_summary",
        "metacognitive_effects",
        "metacognitive_containment_recommendation",
        "semantic_memory_source",
        "procedural_memory_source",
        "semantic_memory_effects",
        "procedural_memory_effects",
        "semantic_memory_lifecycle",
        "procedural_memory_lifecycle",
        "semantic_memory_state",
        "procedural_memory_state",
        "semantic_memory_anchor_refs",
        "semantic_memory_evidence_refs",
        "semantic_memory_use_reason",
        "semantic_memory_non_use_reason",
        "memory_lifecycle_status",
        "memory_review_status",
        "memory_maintenance_status",
        "memory_maintenance_reason",
        "memory_maintenance_fallback_mode",
        "context_compaction_status",
        "cross_session_recall_status",
        "memory_consolidation_status",
        "memory_fixation_status",
        "memory_archive_status",
        "reflection_influence_status",
        "reflection_influence_refs",
        "reflection_influence_summary",
        "reflection_influence_workflow_profile",
        "reviewed_learning_influence_status",
        "reviewed_learning_influence_refs",
        "reviewed_learning_influence_summary",
        "reviewed_learning_influence_reason",
        "procedural_artifact_status",
        "procedural_artifact_ref",
        "procedural_artifact_version",
        "procedural_artifact_summary",
        "mind_disagreement_status",
        "mind_validation_checkpoints",
        "capability_decision_status",
        "capability_decision_objective",
        "capability_decision_reason",
        "capability_decision_selected_mode",
        "capability_decision_authorization_status",
        "capability_decision_fallback_mode",
        "capability_decision_tool_class",
        "capability_decision_handoff_mode",
        "capability_decision_eligible_capabilities",
        "capability_decision_selected_capabilities",
        "request_identity_status",
        "request_active_mission",
        "request_executive_posture",
        "request_authority_level",
        "request_risk_profile",
        "request_reversibility_mode",
        "request_confirmation_mode",
        "request_identity_summary",
        "request_identity_policy_refs",
        "requested_autonomy_level",
        "max_autonomy_level",
        "effective_autonomy_level",
        "autonomy_ladder_status",
        "max_autonomy_capability_mode",
        "autonomy_human_confirmation_required",
        "autonomy_confirmation_mode",
        "autonomy_allowed_runtime_actions",
        "autonomy_blocked_runtime_actions",
        "autonomy_policy_refs",
        "autonomy_summary",
        "autonomy_automatic_promotion_allowed",
        "autonomy_core_mutation_allowed",
        "adaptive_intervention_status",
        "adaptive_intervention_reason",
        "adaptive_intervention_trigger",
        "adaptive_intervention_selected_action",
        "adaptive_intervention_expected_effect",
        "adaptive_intervention_effects",
        "cognitive_strategy_shift_applied",
        "cognitive_strategy_shift_summary",
        "cognitive_strategy_shift_trigger",
        "cognitive_strategy_shift_effects",
        "continuity_action",
        "continuity_reason",
        "open_loops",
        "continuity_source",
        "continuity_target_mission_id",
        "continuity_target_goal",
        "continuity_replay_status",
        "continuity_recovery_mode",
        "continuity_resume_point",
        "project_ref",
        "objective_ref",
        "work_item_refs",
        "checkpoint_refs",
        "artifact_refs",
        "objective_status",
        "next_action_ref",
        "contract_validation_status",
        "contract_validation_errors",
        "contract_validation_retry_applied",
    ),
)

MISSION_STATE_SCHEMA = CanonicalSchema(
    name="MissionStateSchema",
    contract_name="MissionStateContract",
    required_fields=(
        "mission_id",
        "mission_goal",
        "mission_status",
        "checkpoints",
        "updated_at",
    ),
    optional_fields=(
        "created_at",
        "session_origin",
        "active_tasks",
        "related_memories",
        "related_artifacts",
        "recent_plan_steps",
        "semantic_brief",
        "semantic_focus",
        "identity_continuity_brief",
        "open_loops",
        "last_decision_frame",
        "ecosystem_state_status",
        "active_work_items",
        "active_artifact_refs",
        "open_checkpoint_refs",
        "surface_presence",
        "ecosystem_state_summary",
        "linked_surface_ids",
        "active_surface_id",
        "last_surface_id",
        "surface_continuity_status",
        "surface_identity_conflict_flags",
        "project_ref",
        "objective_ref",
        "work_item_refs",
        "checkpoint_refs",
        "artifact_refs",
        "objective_status",
        "next_action_ref",
        "priority_level",
        "owner_context",
        "completion_criteria",
    ),
)

WORK_ITEM_STATE_SCHEMA = CanonicalSchema(
    name="WorkItemStateSchema",
    contract_name="WorkItemStateContract",
    required_fields=(
        "work_item_ref",
        "work_item_status",
        "mission_id",
    ),
    optional_fields=(
        "transition",
        "next_action_ref",
        "checkpoint_refs",
        "memory_write_mode",
    ),
)

ARTIFACT_LIFECYCLE_STATE_SCHEMA = CanonicalSchema(
    name="ArtifactLifecycleStateSchema",
    contract_name="ArtifactLifecycleStateContract",
    required_fields=(
        "artifact_ref",
        "artifact_status",
        "mission_id",
    ),
    optional_fields=(
        "transition",
        "artifact_version",
        "owner_mission_id",
        "objective_ref",
        "work_item_ref",
        "replacement_artifact_ref",
        "rollback_plan_ref",
        "checkpoint_refs",
        "memory_write_mode",
    ),
)

ARTIFACT_RESULT_SCHEMA = CanonicalSchema(
    name="ArtifactResultSchema",
    contract_name="ArtifactResultContract",
    required_fields=(
        "artifact_id",
        "artifact_type",
        "artifact_status",
        "produced_by",
        "timestamp",
    ),
    optional_fields=(
        "location_ref",
        "summary",
        "format",
        "mission_id",
        "request_id",
        "quality_flags",
        "related_artifacts",
    ),
)

SANDBOX_TO_RELEASE_CHECKLIST_SCHEMA = CanonicalSchema(
    name="SandboxToReleaseChecklistSchema",
    contract_name="SandboxToReleaseChecklistContract",
    required_fields=(
        "checklist_id",
        "evolution_proposal_id",
        "release_scope",
        "checklist_status",
        "human_review_status",
        "required_gates",
    ),
    optional_fields=(
        "evidence_refs",
        "proposed_tests",
        "rollback_plan_ref",
        "blockers",
        "candidate_type",
        "candidate_identity_ref",
        "candidate_version",
        "sandbox_eval_ref",
        "sandbox_eval_status",
        "sandbox_required",
        "release_gate_required",
        "automatic_promotion_allowed",
        "core_mutation_allowed",
    ),
    notes=(
        "Executable sandbox-to-release checklist; not a promotion authorization.",
    ),
)

PROMOTION_GATE_DECISION_SCHEMA = CanonicalSchema(
    name="PromotionGateDecisionSchema",
    contract_name="PromotionGateDecisionContract",
    required_fields=(
        "promotion_gate_id",
        "checklist_id",
        "evolution_proposal_id",
        "release_scope",
        "gate_status",
        "decision",
        "release_conclusion",
        "required_gates",
        "completed_gates",
        "missing_gates",
        "evidence_refs",
        "blockers",
        "human_review_status",
        "promotion_eligible",
    ),
    optional_fields=(
        "human_decision_required",
        "promotion_authorized",
        "automatic_promotion_allowed",
        "core_mutation_allowed",
    ),
    notes=(
        "Executable promotion gate decision; never a human promotion authorization.",
    ),
)

EVOLUTION_PROPOSAL_SCHEMA = CanonicalSchema(
    name="EvolutionProposalSchema",
    contract_name="EvolutionProposalContract",
    required_fields=(
        "evolution_proposal_id",
        "proposal_type",
        "target_scope",
        "hypothesis",
        "expected_gain",
        "timestamp",
    ),
    optional_fields=(
        "source_signals",
        "baseline_refs",
        "risk_hint",
        "requires_sandbox",
        "proposed_tests",
        "promotion_constraints",
        "optimization_scope",
        "optimization_target_kind",
        "optimization_candidate_status",
        "optimization_safety_status",
        "optimization_blockers",
        "candidate_refs",
        "refinement_vectors",
        "evaluation_matrix",
        "selection_criteria",
        "strategy_context",
    ),
)

EVOLUTION_DECISION_SCHEMA = CanonicalSchema(
    name="EvolutionDecisionSchema",
    contract_name="EvolutionDecisionContract",
    required_fields=(
        "evolution_decision_id",
        "evolution_proposal_id",
        "decision",
        "comparison_summary",
        "timestamp",
    ),
    optional_fields=(
        "promoted_to",
        "rollback_plan_ref",
        "governance_refs",
        "stability_score",
        "risk_score",
        "notes",
        "optimization_scope",
        "optimization_target_kind",
        "optimization_readiness",
        "optimization_release_status",
        "optimization_safety_status",
        "optimization_blockers",
        "baseline_label",
        "candidate_label",
        "selected_candidate_label",
        "selection_criteria",
        "baseline_metrics",
        "candidate_metrics",
        "metric_deltas",
    ),
)

VOICE_SESSION_START_SCHEMA = CanonicalSchema(
    name="VoiceSessionStartSchema",
    contract_name="VoiceSessionStartContract",
    required_fields=(),
    optional_fields=(),
    notes=(
        "Placeholder canonical schema until field-level voice contracts are formalized in code.",
    ),
)

VOICE_TURN_SCHEMA = CanonicalSchema(
    name="VoiceTurnSchema",
    contract_name="VoiceTurnContract",
    required_fields=(),
    optional_fields=(),
    notes=(
        "Placeholder canonical schema until field-level voice contracts are formalized in code.",
    ),
)

VOICE_RESPONSE_SCHEMA = CanonicalSchema(
    name="VoiceResponseSchema",
    contract_name="VoiceResponseContract",
    required_fields=(),
    optional_fields=(),
    notes=(
        "Placeholder canonical schema until field-level voice contracts are formalized in code.",
    ),
)
